---
name: New Collaboration
description: Collaborate with DMind.ai
title: "[Collaboration] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in being listed under "Projects Using DMind"!
        
        DMind is an open-source AGI research organization focused on next-generation digital finance. We showcase projects that integrate or build with DMind's technology.
        
        Please provide the following information about your project:
  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: Your project's name (max 50 characters)
      placeholder: My Awesome Project
    validations:
      required: true
  - type: input
    id: project-url
    attributes:
      label: Project URL
      description: Your project's website or repository URL
      placeholder: https://github.com/username/project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: A brief description of your project (max 200 characters)
      placeholder: What does your project do?
    validations:
      required: true
  - type: input
    id: logo-url
    attributes:
      label: Logo URL
      description: Direct URL to your project's logo (PNG/JPG, max 200x200px)
      placeholder: https://example.com/logo.png
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## What's Next?
        - Please wait patiently while we review your submission
        - We typically respond within 1-2 business days
        - For urgent inquiries, contact us at [contact@dmind.ai](mailto:contact@dmind.ai)
        - Once approved, your project will appear on [dmind.ai](https://dmind.ai) 