name: Collaboration Handler

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  validate-issue:
    if: startsWith(github.event.issue.title, '[Collaboration]')
    runs-on: ubuntu-latest
    steps:
      - name: Validate Issue
        run: |
          BODY="$(jq -r .issue.body < $GITHUB_EVENT_PATH)"
          echo "ISSUE BODY:"
          echo "$BODY"

          PROJECT_NAME=$(echo "$BODY" | awk 'tolower($0) ~ /project name/{getline; print}' | xargs)
          PROJECT_URL=$(echo "$BODY" | awk 'tolower($0) ~ /project url/{getline; print}' | xargs)
          DESCRIPTION=$(echo "$BODY" | awk 'tolower($0) ~ /project description/{getline; print}' | xargs)
          LOGO_URL=$(echo "$BODY" | awk 'tolower($0) ~ /logo url/{getline; print}' | xargs)

          echo "Extracted PROJECT_NAME: $PROJECT_NAME"
          echo "Extracted PROJECT_URL: $PROJECT_URL"
          echo "Extracted DESCRIPTION: $DESCRIPTION"
          echo "Extracted LOGO_URL: $LOGO_URL"

          if [ -z "$PROJECT_NAME" ]; then
            echo "Error: Project name is required"
            exit 1
          fi
          if [ -z "$PROJECT_URL" ]; then
            echo "Error: Project URL is required"
            exit 1
          fi
          if [ -z "$DESCRIPTION" ]; then
            echo "Error: Description is required"
            exit 1
          fi
          if [ -z "$LOGO_URL" ]; then
            echo "Error: Logo URL is required"
            exit 1
          fi

  process-approved:
    needs: validate-issue
    if: contains(github.event.issue.labels.*.name, 'approved')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Process Collaboration
        run: |
          BODY="$(jq -r .issue.body < $GITHUB_EVENT_PATH)"
          echo "ISSUE BODY:"
          echo "$BODY"

          PROJECT_NAME=$(echo "$BODY" | awk 'tolower($0) ~ /project name/{getline; print}' | xargs)
          PROJECT_URL=$(echo "$BODY" | awk 'tolower($0) ~ /project url/{getline; print}' | xargs)
          DESCRIPTION=$(echo "$BODY" | awk 'tolower($0) ~ /project description/{getline; print}' | xargs)
          LOGO_URL=$(echo "$BODY" | awk 'tolower($0) ~ /logo url/{getline; print}' | xargs)

          echo "Extracted PROJECT_NAME: $PROJECT_NAME"
          echo "Extracted PROJECT_URL: $PROJECT_URL"
          echo "Extracted DESCRIPTION: $DESCRIPTION"
          echo "Extracted LOGO_URL: $LOGO_URL"

          mkdir -p collaborators/logos

          EXT="${LOGO_URL##*.}"
          curl -L -o "collaborators/logos/${{ github.event.issue.number }}.${EXT}" "$LOGO_URL"

          echo "{\n  \"name\": \"$PROJECT_NAME\",\n  \"url\": \"$PROJECT_URL\",\n  \"description\": \"$DESCRIPTION\",\n  \"logo\": \"${{ github.event.issue.number }}.${EXT}\",\n  \"addedAt\": \"${{ github.event.issue.created_at }}\"\n}" > "collaborators/${{ github.event.issue.number }}.json"

          node scripts/update-website.js

          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Add collaborator: $PROJECT_NAME"
          git push 