name: Collaboration Handler

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  validate-issue:
    if: startsWith(github.event.issue.title, '[Collaboration]')
    runs-on: ubuntu-latest
    steps:
      - name: Validate Issue
        run: |
          if [ -z "${{ github.event.issue.body.project-name }}" ]; then
            echo "Error: Project name is required"
            exit 1
          fi
          if [ -z "${{ github.event.issue.body.project-url }}" ]; then
            echo "Error: Project URL is required"
            exit 1
          fi
          if [ -z "${{ github.event.issue.body.description }}" ]; then
            echo "Error: Description is required"
            exit 1
          fi
          if [ -z "${{ github.event.issue.body.logo-url }}" ]; then
            echo "Error: Logo URL is required"
            exit 1
          fi

  process-approved:
    needs: validate-issue
    if: github.event.issue.labels.*.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Process Collaboration
        run: |
          # Create directories if they don't exist
          mkdir -p collaborators/logos
          
          # Download and validate logo
          curl -o "collaborators/logos/${{ github.event.issue.number }}.png" "${{ github.event.issue.body.logo-url }}"
          
          # Create JSON
          echo '{
            "name": "${{ github.event.issue.body.project-name }}",
            "url": "${{ github.event.issue.body.project-url }}",
            "description": "${{ github.event.issue.body.description }}",
            "logo": "${{ github.event.issue.number }}.png",
            "addedAt": "${{ github.event.issue.created_at }}"
          }' > "collaborators/${{ github.event.issue.number }}.json"
          
          # Update website
          node scripts/update-website.js
          
          # Commit and push changes
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Add collaborator: ${{ github.event.issue.body.project-name }}"
          git push 